# 1. The name of our robot's task
name: My First Automation Robot

# 2. The Trigger: Wake up whenever code is pushed to any branch
on: 
  workflow_dispatch:
# 3. The Work: What the robot actually does
jobs:
  run-robot-tasks:
    # Use a fresh, clean Ubuntu computer in GitHub's cloud
    runs-on: ubuntu-latest
    
    steps:
      # Step A: Print a simple greeting in the logs
      - name: Say Hello
        run: echo "Hello! Your GitHub Actions robot is awake and working."

      # Step B: Ask the robot to print out the Git branch name
        env : My_Pass
      - name: Print the GitHub Variable
        # This will print the exact plain text stored in your variable
        run: echo "The Salesforce User is ${{ vars.MY_USER }}"

      - name: Print the GitHub Secret (Secured)
        # This will run, but GitHub will display '***' in the logs to protect it!
        run: echo "The Salesforce Secret Key is ${{ secrets.MY_USE_PASS }}"
